name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: doclink-checker
            asset_name: doclink-checker-linux-x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: doclink-checker.exe
            asset_name: doclink-checker-windows-x86_64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: doclink-checker
            asset_name: doclink-checker-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: doclink-checker
            asset_name: doclink-checker-macos-aarch64

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Create release archive
      shell: bash
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} ${{ matrix.asset_name }}
        else
          tar czf ${{ matrix.asset_name }}.tar.gz -C target/${{ matrix.target }}/release ${{ matrix.artifact_name }}
        fi

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ matrix.asset_name }}*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}